name: Kotlin CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar

      - name: Debug workflow
        run: tree; ls -la

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: shadow
          path: app/build/libs/app-all.jar
